// http_server.c
// HTTP server with embedded web assets

#include <string.h>
#include "esp_http_server.h"
#include "esp_vfs.h"

#include "http_server.h"
#include "api_handler.h"
#include "api_config.h"
#include "log_levels.h"
#include "logger.h"
#include "system_config.h"
#include "watchdog.h"

// ============================================================
// Embedded File Declarations (generated by CMake)
// ============================================================
extern const unsigned char _binary_index_html_start[] asm("_binary_index_html_start");
extern const unsigned char _binary_index_html_end[]   asm("_binary_index_html_end");
extern const unsigned char _binary_automation_html_start[] asm("_binary_automation_html_start");
extern const unsigned char _binary_automation_html_end[]   asm("_binary_automation_html_end");
extern const unsigned char _binary_config_html_start[] asm("_binary_config_html_start");
extern const unsigned char _binary_config_html_end[]   asm("_binary_config_html_end");
extern const unsigned char _binary_calibration_html_start[] asm("_binary_calibration_html_start");
extern const unsigned char _binary_calibration_html_end[]   asm("_binary_calibration_html_end");
extern const unsigned char _binary_api_doc_html_start[] asm("_binary_api_doc_html_start");
extern const unsigned char _binary_api_doc_html_end[]   asm("_binary_api_doc_html_end");
extern const unsigned char _binary_style_css_start[] asm("_binary_style_css_start");
extern const unsigned char _binary_style_css_end[]   asm("_binary_style_css_end");
// ============================================================
// JavaScript File Declarations
// ============================================================
// Core
extern const unsigned char _binary_core_js_start[] asm("_binary_core_js_start");
extern const unsigned char _binary_core_js_end[]   asm("_binary_core_js_end");

// Chart
extern const unsigned char _binary_chart_js_start[] asm("_binary_chart_js_start");
extern const unsigned char _binary_chart_js_end[]   asm("_binary_chart_js_end");

// Dashboard
extern const unsigned char _binary_dashboard_js_start[] asm("_binary_dashboard_js_start");
extern const unsigned char _binary_dashboard_js_end[]   asm("_binary_dashboard_js_end");

// Automation
extern const unsigned char _binary_automation_js_start[] asm("_binary_automation_js_start");
extern const unsigned char _binary_automation_js_end[]   asm("_binary_automation_js_end");

// Config
extern const unsigned char _binary_config_js_start[] asm("_binary_config_js_start");
extern const unsigned char _binary_config_js_end[]   asm("_binary_config_js_end");

// Calibration
extern const unsigned char _binary_calibration_js_start[] asm("_binary_calibration_js_start");
extern const unsigned char _binary_calibration_js_end[]   asm("_binary_calibration_js_end");

// API Docs
extern const unsigned char _binary_api_docs_js_start[] asm("_binary_api_docs_js_start");
extern const unsigned char _binary_api_docs_js_end[]   asm("_binary_api_docs_js_end");

// Router
extern const unsigned char _binary_router_js_start[] asm("_binary_router_js_start");
extern const unsigned char _binary_router_js_end[]   asm("_binary_router_js_end");

// Favicon
extern const unsigned char _binary_favicon_ico_start[] asm("_binary_favicon_ico_start");
extern const unsigned char _binary_favicon_ico_end[]   asm("_binary_favicon_ico_end");

// ============================================================
// Static Variables
// ============================================================
static httpd_handle_t server = NULL;

// ============================================================
// Helper: Serve Embedded File
// ============================================================
static esp_err_t serve_embedded_file(httpd_req_t *req, 
                                     const unsigned char *start, 
                                     const unsigned char *end,
                                     const char *mime_type) {
    size_t len = end - start;
    httpd_resp_set_type(req, mime_type);
    httpd_resp_send(req, (const char *)start, len);
    return ESP_OK;
}

// ============================================================
// Embedded File Handlers
// ============================================================
static esp_err_t index_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_index_html_start, 
                               _binary_index_html_end, 
                               "text/html");
}

static esp_err_t automation_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_automation_html_start, 
                               _binary_automation_html_end, 
                               "text/html");
}

static esp_err_t config_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_config_html_start, 
                               _binary_config_html_end, 
                               "text/html");
}

static esp_err_t calibration_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_calibration_html_start, 
                               _binary_calibration_html_end, 
                               "text/html");
}

static esp_err_t api_doc_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_api_doc_html_start, 
                               _binary_api_doc_html_end, 
                               "text/html");
}

static esp_err_t style_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_style_css_start, 
                               _binary_style_css_end, 
                               "text/css");
}


// ============================================================
// JavaScript File Handlers
// ============================================================
static esp_err_t core_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_core_js_start, 
                               _binary_core_js_end, 
                               "application/javascript");
}

static esp_err_t dashboard_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_dashboard_js_start, 
                               _binary_dashboard_js_end, 
                               "application/javascript");
}

static esp_err_t automation_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_automation_js_start, 
                               _binary_automation_js_end, 
                               "application/javascript");
}

static esp_err_t config_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_config_js_start, 
                               _binary_config_js_end, 
                               "application/javascript");
}

static esp_err_t calibration_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_calibration_js_start, 
                               _binary_calibration_js_end, 
                               "application/javascript");
}

static esp_err_t api_docs_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_api_docs_js_start, 
                               _binary_api_docs_js_end, 
                               "application/javascript");
}

static esp_err_t router_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_router_js_start, 
                               _binary_router_js_end, 
                               "application/javascript");
}

static esp_err_t chart_js_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_chart_js_start, 
                               _binary_chart_js_end, 
                               "application/javascript");
}

static esp_err_t favicon_handler(httpd_req_t *req) {
    return serve_embedded_file(req, 
                               _binary_favicon_ico_start, 
                               _binary_favicon_ico_end, 
                               "image/x-icon");
}

// ============================================================
// Public Functions
// ============================================================

void webserver_init(void) {
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.lru_purge_enable = true;
    config.max_uri_handlers = 64;
    config.stack_size = STACK_SIZE_WEBSERVER;
    
    if (httpd_start(&server, &config) == ESP_OK) {
        APP_LOG_I("HTTP server started on port %d", config.server_port);
        
        // ============================================================
        // Register HTML Routes
        // ============================================================
        httpd_uri_t index_uri = {
            .uri = "/",
            .method = HTTP_GET,
            .handler = index_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &index_uri);
        
        httpd_uri_t index_html_uri = {
            .uri = "/index.html",
            .method = HTTP_GET,
            .handler = index_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &index_html_uri);
        
        httpd_uri_t automation_uri = {
            .uri = "/automation.html",
            .method = HTTP_GET,
            .handler = automation_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &automation_uri);
        
        httpd_uri_t config_uri = {
            .uri = "/config.html",
            .method = HTTP_GET,
            .handler = config_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &config_uri);
        
        httpd_uri_t calibration_uri = {
            .uri = "/calibration.html",
            .method = HTTP_GET,
            .handler = calibration_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &calibration_uri);
        
        httpd_uri_t api_doc_uri = {
            .uri = "/api_doc.html",
            .method = HTTP_GET,
            .handler = api_doc_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &api_doc_uri);
        
        // ============================================================
        // Register Static Assets (CSS, JS)
        // ============================================================
        httpd_uri_t style_uri = {
            .uri = "/style.css",
            .method = HTTP_GET,
            .handler = style_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &style_uri);

        // ============================================================
        // Register JavaScript Routes (same pattern as app_uri)
        // ============================================================
        httpd_uri_t core_js_uri = {
            .uri = "/js/core.js",
            .method = HTTP_GET,
            .handler = core_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &core_js_uri);

        httpd_uri_t dashboard_js_uri = {
            .uri = "/js/dashboard.js",
            .method = HTTP_GET,
            .handler = dashboard_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &dashboard_js_uri);

        httpd_uri_t automation_js_uri = {
            .uri = "/js/automation.js",
            .method = HTTP_GET,
            .handler = automation_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &automation_js_uri);

        httpd_uri_t config_js_uri = {
            .uri = "/js/config.js",
            .method = HTTP_GET,
            .handler = config_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &config_js_uri);

        httpd_uri_t calibration_js_uri = {
            .uri = "/js/calibration.js",
            .method = HTTP_GET,
            .handler = calibration_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &calibration_js_uri);

        httpd_uri_t api_docs_js_uri = {
            .uri = "/js/api_docs.js",
            .method = HTTP_GET,
            .handler = api_docs_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &api_docs_js_uri);

        httpd_uri_t router_js_uri = {
            .uri = "/js/router.js",
            .method = HTTP_GET,
            .handler = router_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &router_js_uri);

        httpd_uri_t chart_js_uri = {
            .uri = "/js/chart.js",
            .method = HTTP_GET,
            .handler = chart_js_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &chart_js_uri);

        httpd_uri_t favicon_uri = {
            .uri = "/favicon.ico",
            .method = HTTP_GET,
            .handler = favicon_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(server, &favicon_uri);

       // ============================================================
        // Register API Endpoints
        // ============================================================
        register_api_endpoints(server);
        
        // ============================================================
        // Register with Watchdog
        // ============================================================
        watchdog_register_module(WDT_MODULE_WEBSERVER, 10);

       APP_LOG_I("Web server initialized with embedded assets");
    } else {
        APP_LOG_E("Failed to start HTTP server");
    }
}

httpd_handle_t webserver_get_handle(void) {
    return server;
}

void webserver_register_uri(httpd_uri_t *uri) {
    if (server && uri) {
        httpd_register_uri_handler(server, uri);
    }
}